# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Marvel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Marvel
  pod 'Alamofire', '~> 4.7'
  pod 'CryptoSwift'
  
  target 'MarvelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
